CUSTOM_ITEMS: dict[str,str] = {}

CUSTOM_ITEMS["coin"] = "{{id: \"clock\", tag: {{CustomModelData: 2670001, display: {{Name: '{{\"text\":\"Coin\",\"italic\":false}}'}}}}, Count: {0}}}"
CUSTOM_ITEMS["bag"] = "{{id: \"clock\", tag: {{CustomModelData: 2670002, display: {{Name: '{{\"text\":\"Coin Bag\",\"italic\":false}}'}}}}, Count: {0}}}"
CUSTOM_ITEMS["p_key"] = "{{id: \"clock\", tag: {{CustomModelData: 2670003, display: {{Name: '{{\"text\":\"Disastrous Studios Key\", \"italic\":false}}'}}}}, Count: {0}}}"
CUSTOM_ITEMS["d_key"] = "{{id: \"clock\", tag: {{CustomModelData: 2670004, display: {{Name: '{{\"text\":\"Blood-Stained Key\", \"italic\":false}}'}}}}, Count: {0}}}"
CUSTOM_ITEMS["a_key"] = "{{id: \"clock\", tag: {{CustomModelData: 2670008, display: {{Name: '{{\"text\":\"Key to the Past\", \"italic\":false}}'}}}}, Count: {0}}}"
CUSTOM_ITEMS["dc_key"] = "{{id: \"clock\", tag: {{CustomModelData: 2670009, display: {{Name: '{{\"text\":\"Delusional Key\", \"italic\":false}}'}}}}, Count: {0}}}"
CUSTOM_ITEMS["m_key"] = "{{id: \"clock\", tag: {{CustomModelData: 2670010, display: {{Name: '{{\"text\":\"Jewel-Encrusted Key\", \"italic\":false}}'}}}}, Count: {0}}}"
CUSTOM_ITEMS["p_pile"] = "{{id: \"clock\", tag: {{CustomModelData: 2670005, display: {{Name: '{{\"text\":\"Pile of Potatoes\", \"italic\":false}}'}}}}, Count: {0}}}"
CUSTOM_ITEMS["p_barrel"] = "{{id: \"clock\", tag: {{CustomModelData: 2670006, display: {{Name: '{{\"text\":\"Barrel of Potatoes\", \"italic\":false}}'}}}}, Count: {0}}}"
CUSTOM_ITEMS["book_v"] = "{{id: \"clock\", tag: {{CustomModelData: 2670007, display: {{Name: '{{\"text\":\"Book Token\", \"italic\":false}}'}}}}, Count: {0}}}"
CUSTOM_ITEMS["burger"] = "{{id: \"cooked_beef\", tag: {{CustomModelData: 2670001, display: {{Name: '{{\"text\":\"Hamburger\", \"italic\":false}}'}}}}, Count: {0}}}"
CUSTOM_ITEMS["salad"] = "{{id: \"beetroot_soup\", tag: {{CustomModelData: 2670001, display: {{Name: '{{\"text\":\"Salad\", \"italic\":false}}'}}}}, Count: {0}}}"
CUSTOM_ITEMS["radio"] = "{{id: \"clock\", tag: {{CustomModelData: 2670011, display: {{Name: '{{\"text\":\"Radio\", \"italic\":false}}'}}}}, Count: {0}}}"
CUSTOM_ITEMS["damaged_radio"] = "{{id: \"clock\", tag: {{CustomModelData: 2670012, display: {{Name: '{{\"text\":\"Damaged Radio\", \"italic\":false}}'}}}}, Count: {0}}}"
CUSTOM_ITEMS["toolbox"] = "{{id: \"clock\", tag: {{CustomModelData: 2670013, display: {{Name: '{{\"text\":\"Toolbox\", \"italic\":false}}'}}}}, Count: {0}}}"
CUSTOM_ITEMS["key_shard"] = "{{id: \"clock\", tag: {{CustomModelData: 2670014, display: {{Name: '{{\"text\":\"Key Shard\", \"italic\":false}}'}}}}, Count: {0}}}"

CUSTOM_ITEMS["jewel_pillar"] = "{{id: \"clock\", tag: {{CustomModelData: 2670015, display: {{Name: '{{\"text\":\"Pillar Jewel\", \"italic\":false}}'}}}}, Count: {0}}}"
CUSTOM_ITEMS["jewel_shuriken"] = "{{id: \"clock\", tag: {{CustomModelData: 2670016, display: {{Name: '{{\"text\":\"Shuriken Jewel\", \"italic\":false}}'}}}}, Count: {0}}}"
CUSTOM_ITEMS["jewel_stack"] = "{{id: \"clock\", tag: {{CustomModelData: 2670017, display: {{Name: '{{\"text\":\"Stack Jewel\", \"italic\":false}}'}}}}, Count: {0}}}"
CUSTOM_ITEMS["jewel_swirl"] = "{{id: \"clock\", tag: {{CustomModelData: 2670018, display: {{Name: '{{\"text\":\"Swirl Jewel\", \"italic\":false}}'}}}}, Count: {0}}}"

CUSTOM_ITEMS["Shuriken"] = "{{id: \"clock\", tag: {{CustomModelData: 2670019, display: {{Name: '{{\"text\":\"Shuriken\", \"italic\":false}}'}}}}, Count: {0}}}"
CUSTOM_ITEMS["warden_key"] = "{{id: \"clock\", tag: {{CustomModelData: 2670020, display: {{Name: '{{\"text\":\"Wardens Key\", \"italic\":false}}'}}}}, Count: {0}}}"